### ISSUE TITLE
assertion failed in Mark's latest run all

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#70]
I think the only things I have done since my last successful run are 

- changing `drivetrain:value_as_number_IntegerLiteralValue` in the transformation instruction set to `drivetrain:value_as_number_LiteralValue`
- #69 ... moving OMOP column names out of the Valid Graph Specification and into 'multi object describers'

But I could be wrong :-(

I did pull the latest Drivetrain code (and pushed my Acorn files) immediately before the run logged below.

PS good recipe names!

```
Mark Miller@DESKTOP-LA54B7U MINGW64 ~/Drivetrain/drivetrain (master)
$ sbt
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\Mark Miller\Drivetrain\drivetrain\project
[info] Loading settings from build.sbt ...
[info] Set current project to drivetrain (in build file:/C:/Users/Mark%20Miller/Drivetrain/drivetrain/)
[info] sbt server started at local:sbt-server-7c6aaae4402927d47ff2
sbt:drivetrain> run all
[info] Compiling 3 Scala sources to C:\Users\Mark Miller\Drivetrain\drivetrain\target\scala-2.11\classes ...
[info] Done compiling.
[info] Packaging C:\Users\Mark Miller\Drivetrain\drivetrain\target\scala-2.11\drivetrain_2.11-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running edu.upenn.turbo.DrivetrainDriver all
11:22:06.365 [run-main-0] INFO  edu.upenn.turbo.DrivetrainDriver$ - Updating graph model using file post_icbo_synthea_omop_cnp_transformation_instructions.ttl
11:22:06.657 [run-main-0] INFO  edu.upenn.turbo.DrivetrainDriver$ - Updating graph specification using file turbo_valid_graph_specification.ttl
11:22:07.002 [run-main-0] INFO  edu.upenn.turbo.OntologyLoader$ - Adding ontology https://raw.githubusercontent.com/PennTURBO/Turbo-Ontology/master/ontologies/turbo_merged.owl
11:22:08.921 [run-main-0] INFO  edu.upenn.turbo.DrivetrainDriver$ - Clearing production named graphs...
11:22:09.060 [run-main-0] INFO  edu.upenn.turbo.OntologyLoader$ - Adding ontology https://raw.githubusercontent.com/PennTURBO/Turbo-Ontology/master/ontologies/turbo_merged.owl
11:22:13.886 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorCridHasPartRegDen in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterCridHasPartRegDen in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/alleleMentionsGeneSymbolUri in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/alleleHasValueSpecZygosityUri in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/genomeCridHasPartGenomeCridRegDen in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DiagMentionsIcdTerm in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DiagMentionsSnomedTerm in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.887 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/cancerHasMaterialBasisTumor in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/patientHasPartTumor in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorPartOfPatient in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorCridSymbolPartOfTumorCrid in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorCridDenotesTumor in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorCridHasPartTumorCridSymbol in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/ProcboundStartsBiobankEnc in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterCridDenotesBiobankEncounter in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.888 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterCridHasPartSymbol in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterStartStartsBiobankEncounter in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterSymbolPartOfCrid in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/patientHasRolePuiRole in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/puiRoleRealizesBiobankEncounter in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DNAExtractionProcessHasOutputDNAExtract in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DNAExtractionProcessHasInputSpecimen in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DNAhasGrainDNAExtract in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.889 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DNAIsGenomeOfHomoSapiens in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/alleleIsAboutDNA in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterHasPartCollectionProcess in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/collectionProcessPartOfBiobankEncounter in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/collectionProcessHasInputHomoSapiens in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/collectionProcessHasOutputSpecimen in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/exomeSequenceProcessHasInputDNAExtract in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.890 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/exomeSequenceProcessHasOutputSequenceData in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.891 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/formProcessHasOutputAllele in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.891 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/formProcessHasInputSequenceData in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.891 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/genomeCridSymbolPartOfGenomeCrid in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.891 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/genomeCridHasPartGenomeCridSymbol in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.891 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/genomeCridDenotesSpecimen in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.891 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/BiobankEncHasOutputMeas in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.892 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/DobHasRawDateString in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.892 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/EncStartingTmdHasRawStringVal in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.892 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorCridSymbolHasRepresentation in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.892 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterSymbolHasRepresentation in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.892 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/alleleHasGeneSymbolGeneSymbolPrefix in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/alleleHasGeneSymbolGeneSymbolSuffix in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/alleleHasRepresentation in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/genomeSymbolHasRepresentation in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/diagnosisHasCodingSequence in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/diagnosisIsPrimary in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/diagnosisHasRegistryString in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.893 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/tumorRegDenPartOfTumorCrid in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.894 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/biobankEncounterRegistryDenoterPartOfCrid in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.894 [run-main-0] WARN  edu.upenn.turbo.GraphModelValidator$ - Connection recipe https://github.com/PennTURBO/Drivetrain/genomeCridRegistryDenoterPartOfGenomeCrid in the Graph Specification is not the output of a queued process in the Instruction Set, but it is not a required recipe.
11:22:13.895 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - Drivetrain will now run the following processes in this order:
11:22:13.896 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/Patients
11:22:13.897 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/HealthCareEncounters
11:22:13.897 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/HceParticipation
11:22:13.897 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/HcePrecedence
11:22:13.897 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/HealthCareProcedures
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/HcpParticipation
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/HcpParthood
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/PatientMeasurements
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/PatientMul
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/PatientMeasAboutness
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/PatientMeasParthood
11:22:13.898 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/Diagnosis
11:22:13.899 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/DiagnosisAboutness
11:22:13.899 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/DiagnosisParthood
11:22:13.899 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/Prescription
11:22:13.899 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/RxParthood
11:22:13.899 [run-main-0] INFO  e.upenn.turbo.RunDrivetrainProcess$ - https://github.com/PennTURBO/Drivetrain/RxAboutness
[error] (run-main-0) java.lang.AssertionError: assertion failed
[error] java.lang.AssertionError: assertion failed
[error]         at scala.Predef$.assert(Predef.scala:156)
[error]         at edu.upenn.turbo.GraphModelValidator$.validateGraphSpecificationAgainstOntology(GraphModelValidator.scala:181)
[error]         at edu.upenn.turbo.RunDrivetrainProcess$.runProcess(RunDrivetrainProcess.scala:48)
[error]         at edu.upenn.turbo.RunDrivetrainProcess$.runAllDrivetrainProcesses(RunDrivetrainProcess.scala:451)
[error]         at edu.upenn.turbo.DrivetrainDriver$.runAllDrivetrainProcesses(DrivetrainDriver.scala:158)
[error]         at edu.upenn.turbo.DrivetrainDriver$.main(DrivetrainDriver.scala:50)
[error]         at edu.upenn.turbo.DrivetrainDriver.main(DrivetrainDriver.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]         at java.lang.reflect.Method.invoke(Unknown Source)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Unknown Source)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at sbt.Run$.executeTrapExit(Run.scala:124)
[error]         at sbt.Run.run(Run.scala:77)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1172)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1167)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 28 s, completed Nov 13, 2019 11:22:14 AM
sbt:drivetrain>
```

**Comment by greenguy33** [comment]
More verbose error message created for this error
